REGIME_SNAPSHOTS = {
    "bullish": {
        "date": "2026-03-07",
        "instrument": "NQ",
        "daily_bias": "bullish",
        "h4_bias": "bullish",
        "h1_bias": "bullish",
        "pdh": 18450.25,
        "pdl": 18210.50,
        "onh": 18380.00,
        "onl": 18290.75,
        "pmh": 18500.00,
        "pml": 18100.00,
        "vwap": 18342.50,
        "directional_score": 7,
        "expansion_score": 6,
        "day_quality": "A",
        "above_or_below_vwap": "above",
        "inside_or_outside_prior_day_range": "inside",
        "has_830_news": True,
        "news_bias": "bullish",
        "news_volatility_risk": "medium",
        "premarket_structure": "higher_highs",
        "holds_vwap": True,
        "compression_before_open": False,
        "sweep_detected_preopen": False,
    },
    "bearish": {
        "date": "2026-03-07",
        "instrument": "NQ",
        "daily_bias": "bearish",
        "h4_bias": "bearish",
        "h1_bias": "bearish",
        "pdh": 18450.25,
        "pdl": 18210.50,
        "onh": 18240.00,
        "onl": 18100.00,
        "pmh": 18300.00,
        "pml": 17950.00,
        "vwap": 18180.00,
        "directional_score": 2,
        "expansion_score": 5,
        "day_quality": "B",
        "above_or_below_vwap": "below",
        "inside_or_outside_prior_day_range": "inside",
        "has_830_news": True,
        "news_bias": "bearish",
        "news_volatility_risk": "high",
        "premarket_structure": "lower_lows",
        "holds_vwap": False,
        "compression_before_open": False,
        "sweep_detected_preopen": False,
    },
    "sweep": {
        "date": "2026-03-07",
        "instrument": "NQ",
        "daily_bias": "neutral",
        "h4_bias": "bullish",
        "h1_bias": "bearish",
        "pdh": 18450.25,
        "pdl": 18210.50,
        "onh": 18460.00,
        "onl": 18200.00,
        "pmh": 18470.00,
        "pml": 18190.00,
        "vwap": 18335.00,
        "directional_score": 5,
        "expansion_score": 8,
        "day_quality": "A",
        "above_or_below_vwap": "above",
        "inside_or_outside_prior_day_range": "outside",
        "has_830_news": False,
        "news_bias": "neutral",
        "news_volatility_risk": "low",
        "premarket_structure": "sweep_and_reverse",
        "holds_vwap": True,
        "compression_before_open": True,
        "sweep_detected_preopen": True,
    },
    "range": {
        "date": "2026-03-07",
        "instrument": "NQ",
        "daily_bias": "neutral",
        "h4_bias": "neutral",
        "h1_bias": "neutral",
        "pdh": 18450.25,
        "pdl": 18210.50,
        "onh": 18360.00,
        "onl": 18300.00,
        "pmh": 18380.00,
        "pml": 18280.00,
        "vwap": 18330.00,
        "directional_score": 4,
        "expansion_score": 2,
        "day_quality": "C",
        "above_or_below_vwap": "above",
        "inside_or_outside_prior_day_range": "inside",
        "has_830_news": False,
        "news_bias": "neutral",
        "news_volatility_risk": "low",
        "premarket_structure": "consolidation",
        "holds_vwap": True,
        "compression_before_open": True,
        "sweep_detected_preopen": False,
    },
}


def get_mock_market_snapshot(regime: str = "bullish", date: str = None):
    # Fall back to bullish if an unknown regime is passed
    snapshot = REGIME_SNAPSHOTS.get(regime, REGIME_SNAPSHOTS["bullish"]).copy()
    if date:
        snapshot["date"] = date
    return snapshot
